// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  patientId: __t.string().name("patient_id"),
  eventType: __t.string().name("event_type"),
  severity: __t.string(),
  timestamp: __t.u64(),
  durationMinutes: __t.i32().name("duration_minutes"),
  notes: __t.string(),
});
