// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  scoreId: __t.string().primaryKey().name("score_id"),
  patientId: __t.string().name("patient_id"),
  date: __t.string(),
  score: __t.i32(),
  memoryScore: __t.i32().name("memory_score"),
  engagementScore: __t.i32().name("engagement_score"),
  moodScore: __t.i32().name("mood_score"),
  notes: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
