// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  personId: __t.string().primaryKey().name("person_id"),
  name: __t.string(),
  relation: __t.string(),
  currentCue: __t.string().name("current_cue"),
  photoUrl: __t.string().name("photo_url"),
  createdAt: __t.u64().name("created_at"),
});
