// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  personId: __t.string().name("person_id"),
  boxX: __t.i32().name("box_x"),
  boxY: __t.i32().name("box_y"),
  boxW: __t.i32().name("box_w"),
  boxH: __t.i32().name("box_h"),
  confidence: __t.f64(),
  updatedAt: __t.u64().name("updated_at"),
});
