// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  date: __t.string().primaryKey(),
  patientId: __t.string().name("patient_id"),
  scheduledCount: __t.i32().name("scheduled_count"),
  takenCount: __t.i32().name("taken_count"),
  missedCount: __t.i32().name("missed_count"),
  adherenceRate: __t.i32().name("adherence_rate"),
});
