// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  medicationId: __t.string().primaryKey().name("medication_id"),
  medicineName: __t.string().name("medicine_name"),
  dose: __t.string(),
  triggerTime: __t.u64().name("trigger_time"),
  status: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
