// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  quizSessionId: __t.string().primaryKey().name("quiz_session_id"),
  patientId: __t.string().name("patient_id"),
  accuracyScore: __t.f64().name("accuracy_score"),
  speedScore: __t.f64().name("speed_score"),
  averageScore: __t.f64().name("average_score"),
  questionsTaken: __t.i32().name("questions_taken"),
  createdAt: __t.u64().name("created_at"),
});
