// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  zoneId: __t.string().primaryKey().name("zone_id"),
  centerLat: __t.f64().name("center_lat"),
  centerLng: __t.f64().name("center_lng"),
  radiusMeters: __t.f64().name("radius_meters"),
  label: __t.string(),
  updatedAt: __t.u64().name("updated_at"),
});
