// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  logId: __t.string().primaryKey().name("log_id"),
  sessionId: __t.string().name("session_id"),
  personId: __t.string().name("person_id"),
  timestamp: __t.u64(),
  sentimentScore: __t.f64().name("sentiment_score"),
  dominantEmotion: __t.string().name("dominant_emotion"),
  emotionConfidence: __t.f64().name("emotion_confidence"),
  cueText: __t.string().name("cue_text"),
});
