// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BehaviourEvent = __t.object("BehaviourEvent", {
  eventId: __t.string(),
  patientId: __t.string(),
  eventType: __t.string(),
  severity: __t.string(),
  timestamp: __t.u64(),
  durationMinutes: __t.i32(),
  notes: __t.string(),
});
export type BehaviourEvent = __Infer<typeof BehaviourEvent>;

export const CaretakerIdentity = __t.object("CaretakerIdentity", {
  identity: __t.identity(),
  displayName: __t.string(),
  registeredAt: __t.u64(),
});
export type CaretakerIdentity = __Infer<typeof CaretakerIdentity>;

export const CognitiveScore = __t.object("CognitiveScore", {
  scoreId: __t.string(),
  patientId: __t.string(),
  date: __t.string(),
  score: __t.i32(),
  memoryScore: __t.i32(),
  engagementScore: __t.i32(),
  moodScore: __t.i32(),
  notes: __t.string(),
  createdAt: __t.u64(),
});
export type CognitiveScore = __Infer<typeof CognitiveScore>;

export const KnownPerson = __t.object("KnownPerson", {
  personId: __t.string(),
  name: __t.string(),
  relation: __t.string(),
  currentCue: __t.string(),
  photoUrl: __t.string(),
  createdAt: __t.u64(),
});
export type KnownPerson = __Infer<typeof KnownPerson>;

export const LiveDetection = __t.object("LiveDetection", {
  sessionId: __t.string(),
  personId: __t.string(),
  boxX: __t.i32(),
  boxY: __t.i32(),
  boxW: __t.i32(),
  boxH: __t.i32(),
  confidence: __t.f64(),
  updatedAt: __t.u64(),
});
export type LiveDetection = __Infer<typeof LiveDetection>;

export const Medication = __t.object("Medication", {
  medicationId: __t.string(),
  medicineName: __t.string(),
  dose: __t.string(),
  triggerTime: __t.u64(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type Medication = __Infer<typeof Medication>;

export const MedicationAdherence = __t.object("MedicationAdherence", {
  date: __t.string(),
  patientId: __t.string(),
  scheduledCount: __t.i32(),
  takenCount: __t.i32(),
  missedCount: __t.i32(),
  adherenceRate: __t.i32(),
});
export type MedicationAdherence = __Infer<typeof MedicationAdherence>;

export const MedicationSchedule = __t.object("MedicationSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  medicationId: __t.string(),
});
export type MedicationSchedule = __Infer<typeof MedicationSchedule>;

export const MeetingLog = __t.object("MeetingLog", {
  sessionId: __t.string(),
  personId: __t.string(),
  status: __t.string(),
  cuesJson: __t.string(),
  startedAt: __t.u64(),
});
export type MeetingLog = __Infer<typeof MeetingLog>;

export const MeetingSummary = __t.object("MeetingSummary", {
  sessionId: __t.string(),
  personId: __t.string(),
  summary: __t.string(),
  meetingDate: __t.string(),
  createdAt: __t.u64(),
});
export type MeetingSummary = __Infer<typeof MeetingSummary>;

export const Notification = __t.object("Notification", {
  notificationId: __t.string(),
  type: __t.string(),
  personId: __t.string(),
  message: __t.string(),
  isRead: __t.bool(),
  createdAt: __t.u64(),
});
export type Notification = __Infer<typeof Notification>;

export const PatientIdentity = __t.object("PatientIdentity", {
  identity: __t.identity(),
  registeredAt: __t.u64(),
});
export type PatientIdentity = __Infer<typeof PatientIdentity>;

export const SafeZone = __t.object("SafeZone", {
  zoneId: __t.string(),
  centerLat: __t.f64(),
  centerLng: __t.f64(),
  radiusMeters: __t.f64(),
  label: __t.string(),
  updatedAt: __t.u64(),
});
export type SafeZone = __Infer<typeof SafeZone>;

export const QuizLog = __t.object("QuizLog", {
  quizSessionId: __t.string(),
  patientId: __t.string(),
  accuracyScore: __t.f64(),
  speedScore: __t.f64(),
  averageScore: __t.f64(),
  questionsTaken: __t.i32(),
  createdAt: __t.u64(),
});
export type QuizLog = __Infer<typeof QuizLog>;

export const SentimentLog = __t.object("SentimentLog", {
  logId: __t.string(),
  sessionId: __t.string(),
  personId: __t.string(),
  timestamp: __t.u64(),
  sentimentScore: __t.f64(),
  dominantEmotion: __t.string(),
  emotionConfidence: __t.f64(),
  cueText: __t.string(),
});
export type SentimentLog = __Infer<typeof SentimentLog>;
