// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddKnownPersonReducer from "../add_known_person_reducer";
import AddMedicationReducer from "../add_medication_reducer";
import ClearLiveDetectionReducer from "../clear_live_detection_reducer";
import CreateNewFaceReducer from "../create_new_face_reducer";
import EndMeetingReducer from "../end_meeting_reducer";
import MarkMedicationTakenReducer from "../mark_medication_taken_reducer";
import MarkNotificationReadReducer from "../mark_notification_read_reducer";
import RegisterCaretakerReducer from "../register_caretaker_reducer";
import RegisterPatientReducer from "../register_patient_reducer";
import RemoveMedicationReducer from "../remove_medication_reducer";
import SaveMeetingSummaryReducer from "../save_meeting_summary_reducer";
import SetSafeZoneReducer from "../set_safe_zone_reducer";
import StartMeetingReducer from "../start_meeting_reducer";
import TriggerSafeZoneAlertReducer from "../trigger_safe_zone_alert_reducer";
import UpdateCueReducer from "../update_cue_reducer";
import UpdateLiveDetectionReducer from "../update_live_detection_reducer";
import UpdatePersonDetailsReducer from "../update_person_details_reducer";

export type AddKnownPersonParams = __Infer<typeof AddKnownPersonReducer>;
export type AddMedicationParams = __Infer<typeof AddMedicationReducer>;
export type ClearLiveDetectionParams = __Infer<typeof ClearLiveDetectionReducer>;
export type CreateNewFaceParams = __Infer<typeof CreateNewFaceReducer>;
export type EndMeetingParams = __Infer<typeof EndMeetingReducer>;
export type MarkMedicationTakenParams = __Infer<typeof MarkMedicationTakenReducer>;
export type MarkNotificationReadParams = __Infer<typeof MarkNotificationReadReducer>;
export type RegisterCaretakerParams = __Infer<typeof RegisterCaretakerReducer>;
export type RegisterPatientParams = __Infer<typeof RegisterPatientReducer>;
export type RemoveMedicationParams = __Infer<typeof RemoveMedicationReducer>;
export type SaveMeetingSummaryParams = __Infer<typeof SaveMeetingSummaryReducer>;
export type SetSafeZoneParams = __Infer<typeof SetSafeZoneReducer>;
export type StartMeetingParams = __Infer<typeof StartMeetingReducer>;
export type TriggerSafeZoneAlertParams = __Infer<typeof TriggerSafeZoneAlertReducer>;
export type UpdateCueParams = __Infer<typeof UpdateCueReducer>;
export type UpdateLiveDetectionParams = __Infer<typeof UpdateLiveDetectionReducer>;
export type UpdatePersonDetailsParams = __Infer<typeof UpdatePersonDetailsReducer>;

